
spring.datasource.url=jdbc:postgresql://ep-wild-breeze-atc91l0v-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CqQ8iLOAlVs7
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
razorpay.key.id=rzp_test_SsnqfbbQFrFTRm
razorpay.key.secret=aHMICCcWeXmMGRFiM57Sc4tK