spring.datasource.url=jdbc:postgresql://ep-wild-forest-aqu99lb0-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_xa2lUFzV0sre

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}